name: build full and pypi upload

on:
  push:
    branches: ["main", "build-test"]
  pull_request:

concurrency:
  # prevent empty str
  group: GROUP-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  macos_wheel_m:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS: "arm64"

    - uses: actions/upload-artifact@v7
      with:
        name: wheels-macos-latest
        path: ./wheelhouse/*.whl

  macos_wheel_intel:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS: "x86_64"

    - uses: actions/upload-artifact@v7
      with:
        name: wheels-macos-13
        path: ./wheelhouse/*.whl


  linux_wheel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]
        cw_build: ["cp*manylinux*", "*musllinux*"]


    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.cw_build }}

    - uses: actions/upload-artifact@v7
      with:
        name: wheels-linux-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl


  windows_wheel:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, AMD64, ARM64]

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: build wheels
      uses: pypa/cibuildwheel@v4.1.0
      env:
        CIBW_ARCHS: ${{ matrix.arch }}
        CIBW_SKIP: "pp*"


    - uses: actions/upload-artifact@v7
      with:
        name: wheels-windows-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl


  source_dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v7
      with:
        # technically not a wheel
        name: wheels-source
        path: ./dist/*

  upload_pypi:
    needs: [macos_wheel_m, macos_wheel_intel, linux_wheel, windows_wheel, source_dist]
    runs-on: ubuntu-latest
       # try to publish only if this is a push to stable branch
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

             # - uses: pypa/gh-action-pypi-publish@v1.6.1
             #with:
             #skip_existing: true
             #user: __token__
             #password: ${{ secrets.PYPI_TOKEN }}
